# Generated by Django 4.1.7 on 2023-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='warrentyperiod',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
